### ISSUE TITLE
[Question] Feature question: extract graph as of README

### ISSUE THREAD

**Issue by andreas-electi** [acuarica/evm#148]
## Description
I noticed there is a graph in the README file showing the Control Flow Graph (CFG) of the decompiled smart contract bytecode. Is there a built-in feature or method that extracts a graph?

## Additional Context
- README Location: [README.md](https://github.com/acuarica/evm/blob/main/README.md)
- Graph Type: [splash.png](https://raw.githubusercontent.com/acuarica/evm/refs/heads/main/splash.png)

I've searched through existing issues and documentation but haven't found information about this functionality. Thank you for any guidance!

**Comment by acuarica** [comment]
Hi @andreas-electi, there is no built-in method to extract a graph visualization since this is out of scope. However, for some tests we use graph snapshot tests. This is the one you can find the `README`.

You can find the code to build the graph here https://github.com/acuarica/evm/blob/402028ca8c3a33dbb8498f0200d9af2efbf4f792/test/utils/cfg.ts.

Let me know if this works for you.

**Comment by acuarica** [comment]
Hey @andreas-electi, just pinging here to check whether you were able to solve the issue.

Just to add to the last comment https://github.com/acuarica/evm/issues/148#issuecomment-2539798280, I'm reluctant to include any specific visualization because it would need to be highly customizable. Any graph visualization would be better off in a different library/project using the sevm API.

**Comment by andreas-electi** [comment]
Thanks @acuarica - really appreciate the detailed response. I'll take a look at the code example you shared.
